### ISSUE TITLE
Add `use iso_c_binding` at the top of generated modules

### ISSUE THREAD

**Issue by havogt** [GridTools/c_bindings#37]
Otherwise the pgi compiler will give a strange error message, something like

>PGF90-S-0099-Illegal use of derived type

**Comment by lukasm91** [comment]
Can you paste the generated file that does not compile? I don't think we are missing a `use` in the generated file. Didn't see #38 (we'll discuss there)

**Comment by havogt** [comment]
See #38 for the fix and then talk to pgi who is right. 😉
